### ISSUE TITLE
Any plan to get this working cross platform?

### ISSUE THREAD

**Issue by jchannon** [lukebuehler/CShell#57]
Hi I've downloaded the binaries on OSX but running `mono Cshell.exe` results in `The entry point method could not be loaded`

Any plan to get this working cross platform?

**Comment by lukebuehler** [comment]
No, unfortunately mono/linux/OSX is not supported. Because CShell uses WPF
which is not supported in mono.

**Comment by jchannon** [comment]
Ah that's a real shame :cry:

**Comment by lonix1** [comment]
There is a cross-plaform UI toolkit based on WPF called [Avalonia](https://github.com/AvaloniaUI/Avalonia).

Many of us are now on linux because .NET Core works everywhere. There is nothing at all like this on linux, so it would be great to see it supported someday.

(@jchannon Did you find a repl tool that works in osx / *nix / mono ?)
