### ISSUE TITLE
License 

### ISSUE THREAD

**Issue by buybackoff** [lukebuehler/CShell#75]
Is there a particular reason why this project is GPL? It is a high quality and useful piece of work, but all its ascendants - Gemini, ScriptCS, Mono.Cecil, AvalonDock are all permissive and not viral. It just takes some time to assemble the pieces into another CShell clone and this time looks like a waste.  There used to be an issue with SharpDevelop or Avalon a couple of years ago, but they are permissive for a long time. I want to adopt and integrate CShell, but unfortunately I can't work with viral licenses if there is any risk they would force my code into GPL zone. I appreciate the idea of FOSS, but there are many examples of good balance, e.g. ZeroMQ/NetMQ is a perfect model.

I have no problems with LPGL and wound't mind publishing my fork and contributing to core development. I have noticed recently that you are interested in F# IDE similar to CShell. There is a project https://github.com/BayardRock/IfSharp (Apache 2.0) that already gives a lot of functionality, but via Web interface. I was thinking to adopt it to Avalon, and CShell looked like a perfect shell for that. I am also planning to open source a data processing library soon and want to adapt the CShell sinks for it.

**Comment by lukebuehler** [comment]
I've meant to change the license of this project for a long time, and I agree it should be more permissive at this point. When it was maintained by Arnova Asset Management the current license made more sense but now since I maintain it privately I want to change it.

I will go with Apache 2.0 since this is what ScriptCS uses and we are building heavily on them at this point.

**Comment by buybackoff** [comment]
Great news! Sounds like I could start integrating it already :+1:
